spring.datasource.url=jdbc:mysql://localhost:3306/controle_produtos
spring.datasource.username=root
spring.datasource.password= Ej101411!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
